### ISSUE TITLE
Burn integration test build behaviors were lost in migration

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6664]
Need to make sure that all of the debugging settings are enabled and all log files are zipped up for the burn integration tests during a CI build. Here is the appveyor.yml from the integration repo:

```
image: Visual Studio 2019

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: skip
  RuntimeTestsEnabled: true


install:
  - reg add HKLM\Software\Policies\Microsoft\Windows\Installer /t REG_SZ /v Logging /d voicewarmupx /f
  - reg add HKLM\Software\WOW6432Node\Policies\Microsoft\Windows\Installer /t REG_SZ /v Logging /d voicewarmupx /f

build_script:
  - appveyor.cmd

test: off

skip_branch_with_pr: true
skip_tags: true

on_finish:
  - ps: 7z a ('logs_' + (Get-Date).tostring("yyyyMMddHHmmss") + '.zip') $env:TEMP\*.log $env:TEMP\..\*.log
  - ps: Push-AppveyorArtifact logs_*.zip
```
