### ISSUE TITLE
SolutionDir variable works on local machine but not on github actions

### ISSUE THREAD

**Issue by BryanCrotaz** [wixtoolset/issues#7816]
Wix 4.0.2

Error on github actions:
```
Error: D:\a\Client\Client\AgentSetupWix4\AgentComponents.wxs(5): error WIX0150: Undefined preprocessor variable '$(SolutionDir)'. [D:\a\Client\Client\AgentSetupWix4\AgentSetupWix4.wixproj]
Error: D:\a\Client\Client\AgentSetupWix4\AgentComponents.wxs(18): error WIX0150: Undefined preprocessor variable '$(SolutionDir)'. [D:\a\Client\Client\AgentSetupWix4\AgentSetupWix4.wixproj]
```

This is the script:
```yaml
  deploy-windows32:
#    needs: buildAndTestWindows
    runs-on: windows-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Cache Nuget global package store
      id: cache-nuget
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Force restore nuget
      run: dotnet restore

    - name: Build app for release
      run: msbuild AgentService\AgentService.csproj -t:rebuild -property:Configuration=Release -p:Version=1.0.0.1

    - name: Debug
      run: dir AgentSetupWix4

    - name: Build installer for release
      run: msbuild AgentSetupWix4\AgentSetupWix4.wixproj -verbosity:diag -t:build -property:Configuration=Release
```

.wixproj
```xml
<Project Sdk="WixToolset.Sdk/4.0.2" TreatWarningsAsErrors="true" Name="Agent">
  <PropertyGroup>
    <PreBuildEvent>
    </PreBuildEvent>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference 
			Include="$(SolutionDir)AgentService\AgentService.csproj" 
			Publish="true" 
		/>
	</ItemGroup>
</Project>
```

```xml
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
	<ComponentGroup Id="AgentServiceFiles" Directory="INSTALLFOLDER">
  	  <Component Id="ServiceExe">
        <File 
			BindPath="$(SolutionDir)DisplaySureAgentService\bin\release\net7.0\publish\win-x64" 
			Source="DisplaySureAgentService.exe"/>
		<ServiceInstall 
			Name="DisplaySureAgent"
			DisplayName="Display Sure Agent"
			Type="ownProcess"
			Start="auto"
			ErrorControl="normal"	  
		/>
		<!-- <ServiceControl/> -->
	  </Component>
		<Component Id="AppSettings">
			<File
				BindPath="$(SolutionDir)DisplaySureAgentService\bin\release\net7.0\publish\win-x64"
				Source="appsettings.json"/>
		</Component>
	</ComponentGroup>
  </Fragment>
</Wix>
```
